backend:
  name: vercel # Use the Vercel backend
  branch: main # Your main branch in GitHub

media_folder: "public/uploads" # Where to store images
public_folder: "/uploads" # How to access images

collections:
  - name: "blog" # A collection named "blog"
    label: "Blog" # What to call it in the UI
    folder: "src/content/blog" # Where to save the files
    create: true # Allow creating new posts
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each post
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}