# This tells the CMS to connect to your GitHub repository using the Vercel backend
backend:
  name: vercel # This line has been changed from git-gateway
  branch: main

# This tells the CMS where to upload images you add to your articles
media_folder: "public/uploads"
public_folder: "/uploads"

# This defines the "collections" of content you can edit. We only have one: Posts.
collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/posts
    label: "Posts" # Used in the UI
    folder: "src/content/posts" # The folder where your articles will be stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Publish Date", name: "publishDate", widget: "datetime"}
      - {label: "Cover Image", name: "coverImage", widget: "image"}
      - {label: "Tags", name: "tags", widget: "list", default: ["others"]}
      - {label: "Body", name: "body", widget: "markdown"}